name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to print'
        required: false
        type: string
        default: "Hello, World! I love Seema Sharam ❤️"
  
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "dasd ${{ inputs.message }}"
